version: 0.2

phases:
  install:
    commands:
      - apt-get update -y
      - apt-get install -y zip unzip
    runtime-versions:
      java: openjdk8
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the NodeJS App
      - cd webscripts
      - zip -r web_deploy.zip .
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  type: zip
  files:
    - "**/*"
  base-directory: 'webscripts'
  discard-paths: no