#!/bin/bash
apt-get update -y
curl --silent --location https://rpm.nodesource.com/setup_6.x | bash -
apt-get install -y nodejs npm
npm install -g forever
npm install pm2 -g
rm -rf /nodeapp
mkdir /nodeapp

